### ISSUE TITLE
Create DDS From Individual MIP Maps (No Header)

### ISSUE THREAD

**Issue by stricq** [KFreon/CSharpImageLibrary#1]
I am loading MIP Maps from a game texture file.  I know the format (either DXT1 or DXT5) the width and the height.  Is it possible to provide a method that will construct the DDS file from this information so that it can be saved to a file?

**Comment by KFreon** [comment]
Sorry, I didn't see this come up.
I'm not sure what you mean.
If you have all that information, you have a dds already right?

**Comment by stricq** [comment]
After further looking I found your method to create a DDS_HEADER and after that it was easy.

**Comment by KFreon** [comment]
Ah excellent :)
