### ISSUE TITLE
v4.1 Bugs

### ISSUE THREAD

**Issue by Kinkojiro** [KFreon/CSharpImageLibrary#11]
Sorry to do this KF, but had some issues...

Copied zip contents to desktop folder.  Open ME3Explorer Extract, run texplorer.

Want to test on DLC folder. 
(1) Exclude All button not working

Set a DLC_CON_END folder.   Runs scans seems ok and fast - when reaches 122/122 pccs:

(2) CTD.

This happens no matter what DLC or Basegame I scan.   The debug window just lists the last pcc scanned.

**Comment by KFreon** [comment]
Wrong GitHub kinko, this is the image engine one :P
I'll move this to the right place when I get back to my PC. 

So... Here's something I forgot to mention: it won't extract DLC, you'll have to use the stable for that. Alpha builds :)


I'll look at the exclude all button, and I assume CTD means crash to desktop. So I'll look at that too.

**Comment by Kinkojiro** [comment]
Ahh. Sorry about that should be WPF.  CTD is crash to desktop.  If u need more info let me know.

**Comment by KFreon** [comment]
[Moved](https://github.com/KFreon/KFreons-ME3Explorer/issues/3)
