### ISSUE TITLE
Unable to launch IE 4.1

### ISSUE THREAD

**Issue by alvarome** [KFreon/CSharpImageLibrary#13]
Hi KF:

Sorry for the dumb question but at 4.1 rev I only have one .exe file. That one is "CSharpImageLibrary.vshost.exe". And launching it (if that makes any sense) seems to do nothing.

Previous revs here were 4.0 & 4.0.2 and both had the "UI_Project.exe" to launch new IE. But,as said, that file is missing in latest rev.

Any help will be much welcomed! :)
Alvaro

**Comment by KFreon** [comment]
On the 4.1 Releases page, there should be two .7z archives.
One is just the CSharpImageLibrary one, but the other is the UI_Project :)

**Comment by alvarome** [comment]
Oppssss.... my bad! :)

Fixed and working! Thanks!
Alvaro
