### ISSUE TITLE
Minor UI Suggestions

### ISSUE THREAD

**Issue by starkgate** [KFreon/CSharpImageLibrary#14]
I had a bit of "fun" testing out the newest rev, here are the results :D.

The LOAD button (very nice neon green effect btw) is placed in a weird spot on my screen. Maybe center it vertically ?
![ui_project_2017-01-31_12-39-35](https://cloud.githubusercontent.com/assets/12874678/22463641/f4e1f8b2-e7b2-11e6-8384-eb4d7a4a04f0.png)
Also, maybe scale it with the window ? So that the entire window always has the same look. You could put a limit to how small the window can be, too.
![ui_project_2017-01-31_12-45-47](https://cloud.githubusercontent.com/assets/12874678/22463697/48fd37d6-e7b3-11e6-8cf9-c61ab420c38a.png)

The About/Credits button disappears when I click on it, reappears once I close the About popup. Not sure if intended ?
![ui_project_2017-01-31_12-39-41](https://cloud.githubusercontent.com/assets/12874678/22463642/f4e52cda-e7b2-11e6-959d-3763979b7ecd.png)

A few issues with the Bulk Conversion window :
1. Changing the format in the Bulk Conversion window also changes the preview in the "normal" conversion window, in the background. Shouldn't both windows be independent ?
2. The layout of the window varies depending on the format you choose, probably because it adapts to the string of text used to describe said format. Have a constant window size instead ?
3. Same as 1., but for the numbers below the preview.
![ui_project_2017-01-31_12-51-46](https://cloud.githubusercontent.com/assets/12874678/22463821/263d694a-e7b4-11e6-93da-c5468bf6bef4.png)
![ui_project_2017-01-31_12-51-50](https://cloud.githubusercontent.com/assets/12874678/22463820/263cd778-e7b4-11e6-9e04-a26cfd564589.png)

I was able to completely drag the preview out of the screen, with no way of dragging it back in (except changing window size). That's probably not something you want :). Perhaps add boundaries to the box you can drag the preview in ? Like, a box with size of 1.5*mipResolution to have a bit of margin. Maybe it's too complicated to implement, in which case feel free to ignore.
![ui_project_2017-01-31_12-58-56](https://cloud.githubusercontent.com/assets/12874678/22464036/2bb50dd2-e7b5-11e6-9114-30cf2ed66fa4.png)
![ui_project_2017-01-31_13-02-07](https://cloud.githubusercontent.com/assets/12874678/22464114/882160fc-e7b5-11e6-8c1f-5ddf836692af.png)

On the 2 screenshots above, you can also see an issue with the "Resolution (MIP Resolution)" string, which overlaps horizontally.

On zooming previews, please change the upscale algorithm to nearest neighbour :). You cannot see the pixels with the current algorithm used. A bit like you would see it in PS.
![ui_project_2017-01-31_13-05-10](https://cloud.githubusercontent.com/assets/12874678/22464204/eb9be0ee-e7b5-11e6-9534-03abe994c8cd.png)

**Comment by KFreon** [comment]
Alrighty, lets see:
**1. Load Button position:** It's a long, complicated, and annoying story, but it's just easier there. I initially wanted it in the center, but I like it this way now.
**2. Load Button Scaling:** I also considered this, but again, it's just complicated with little benefit.
**3. Size limit on Window:** I could just lock it at the size it starts at. Maybe the size of the load button. 
**4. About window weirdness:** All the buttons up there should disappear if their window is showing. It's to avoid issues with being able to open them multiple times.

# Bulk Conversion
**1. Format shared with main:** This is to cut down on the code. I couldn't think of a situation where this would be a problem. But if it is, let me know.
**2. Window layout changes:** It could be the text wrapping. Damn, I'll have to look into that. I don't want it fixed per se, but it shouldn't fluctuate too much.
**3. Other elements shared:** Again, this is to share code. I did consider that maybe this could get a bit annoying, but I figured it wasn't too painful.

## Preview
Ha! Wait...Right clicking doesn't reset it back to normal? Hmmm I'll check that out.

**Resolution string overlap:** I spent a good 5 minutes trying to figure out what you meant, and I'm guessing you mean that the 4096 where there's only the one number is overlapping? That's intended as it's the "true" image dimension. I think having it separate only after you delve into mipmaps is a good way of indicating their not the main image.

**Zoom algorithm:** I doubt I have any control over this. Besides, this thing is not even remotely a stand-in for Photoshop. Just for casual viewing. That said, I'll see what I can do :)

**Comment by starkgate** [comment]
First of all, I wanted to give complete feedback even on tiny issues. So if you feel like it's too much work for too little benefit, I'm absolutely fine with ignoring little issues like these :). eg the bulk conversion thing is distracting, but at least it doesn't break anything.

> Ha! Wait...Right clicking doesn't reset it back to normal? Hmmm I'll check that out.

Didn't know that would be a thing, but I just tried, and it doesn't work either.

> Resolution string overlap

Sorry for being unclear. Hopefully the screenshots below will help clarify :
![ui_project_2017-01-31_15-20-35](https://cloud.githubusercontent.com/assets/12874678/22468532/dc89fbdc-e7c8-11e6-9758-e6e5e8f3b798.png)
![ui_project_2017-01-31_15-20-42](https://cloud.githubusercontent.com/assets/12874678/22468533/dc8dab88-e7c8-11e6-80d3-8eae086efdb7.png)

> Zoom algorithm

The reason I want to be able to see the pixels is to better see compression artifacts. Not a huge deal, it would just be a nice feature to have :).

> About window weirdness

You could also grey out all the buttons as soon as a popup opens. That way the UI still looks the same, with a visual indicator that you're not in the main window anymore.

> Size limit on Window: I could just lock it at the size it starts at. Maybe the size of the load button.

I like this idea. It gets rid of the positioning issue, too.

**Comment by KFreon** [comment]
- There's ctrl+wheel zoom too which zooms into the mouse cursor :)
- I see the issue with the resolution indicators. I'll see what I can do.
- The zoom is handled by scaling the image object itself, not really true zoom, so I don't know if it's possible to see the pixels anyway. Either way, it'll be interesting to see what options there are.
- I meant that the limit would be the size of the button, not that the default is going to be the size of the button :P I still like the button down there.

**Comment by KFreon** [comment]
Ok so:
- Resolution indicator with fixed.
- Zoom quality setting now in the Settings panel.
- Window has a minimum size now, hopefully not too large.
- Bulk Convert window has fixed dimensions.

Will upload new version when I get time.
