### ISSUE TITLE
Bulk Conversion to same format

### ISSUE THREAD

**Issue by starkgate** [KFreon/CSharpImageLibrary#15]
I mentioned having to bulk generate MIPs before, which can't be done with IE for now, because you can only choose to convert to a single format. What about adding a new item in the format list : "Same", which would simply keep the same format, and apply all other operations on the alpha or the MIPs ?
![ui_project_2017-01-31_12-49-06](https://cloud.githubusercontent.com/assets/12874678/22463757/b0b69e1c-e7b3-11e6-9f3d-d21ddc44799e.png)

**Comment by KFreon** [comment]
This is implemented on my end, and I'll upload a new version when I get time.
One thing I'm curious about is whether the other settings will break things in this mode. I don't think they will, but they may require careful consideration before proceeding.

**Comment by starkgate** [comment]
Awesome, thank you so much !
