### ISSUE TITLE
Previews

### ISSUE THREAD

**Issue by starkgate** [KFreon/CSharpImageLibrary#16]
It's me again :D.

Most previews seem broken, they only display a monochrome picture. I've only tested actually converting DXT1 to ATI2, which seems to have worked (ie, the texture displays fine in IE, it's not monochrome).

![ui_project_2017-01-31_13-32-55](https://cloud.githubusercontent.com/assets/12874678/22465112/6b47eb7c-e7ba-11e6-932b-1352378c9096.png)
![ui_project_2017-01-31_13-33-01](https://cloud.githubusercontent.com/assets/12874678/22465116/6b4d5a30-e7ba-11e6-8322-4b5a5c7cb2ca.png)
![ui_project_2017-01-31_13-33-11](https://cloud.githubusercontent.com/assets/12874678/22465114/6b4a1a3c-e7ba-11e6-9a7e-3c139ebdbdbe.png)
![ui_project_2017-01-31_13-33-24](https://cloud.githubusercontent.com/assets/12874678/22465113/6b484d88-e7ba-11e6-9cca-4934f2671c3a.png)
![ui_project_2017-01-31_13-33-29](https://cloud.githubusercontent.com/assets/12874678/22465115/6b4b49ac-e7ba-11e6-8b43-23ec72c8a590.png)

Also, just realized DXT5/DXT1 to PNG/BMP results in a compressed file a few dozen bytes big. That is quite the compression. Do you store the rest of the data in quantum space ?^^

Test files : [Out.zip](https://github.com/KFreon/CSharpImageLibrary/files/741938/Out.zip)

**Comment by KFreon** [comment]
Oh that's my new compression algorithm. Pretty cool right? Throw away all the data! Very compressed, much savings, wow.
I must have broken it somehow...

**Comment by starkgate** [comment]
Haha, who needs textures when you can have a monochrome game ? 1x1 textures, no VRAM needed.

**Comment by KFreon** [comment]
This is fixed on my end. I'll upload a new one when I get some time.

**Comment by KFreon** [comment]
[ImageEngine_TEST.zip](https://github.com/KFreon/CSharpImageLibrary/files/743843/ImageEngine_TEST.zip)
Can I get you to test this one before I update the formal releases? Just to make sure I haven't made further silly mistakes.

**Comment by starkgate** [comment]
I tried several combinations of DXT1/DXT5/ATI2 with all possible outcomes, it seems to work perfectly now. Great :).
