### ISSUE TITLE
BMP/PNG/TIFF/all? to ATI2

### ISSUE THREAD

**Issue by starkgate** [KFreon/CSharpImageLibrary#17]
Weird oversaturation when converting from BMP to ATI2. It's not just a preview glitch, I tested it out. The same thing happens with a PNG and a TIFF to ATI2 conversion. Even more interesting is that all tools I tested seem to have the same issue : I've tried Nvidia DDS plugin, Compressonator, DXTT, IE, Intel DDS Plugin, nvcompress ; all of them oversaturate (some of them swap channels, too...). I'm not sure if it's just me that is stupid, or if there is something really wrong here^^.
![ui_project_2017-02-01_20-49-07](https://cloud.githubusercontent.com/assets/12874678/22523526/06095aa0-e8c0-11e6-9805-96947b6dcc3e.png)
![ui_project_2017-02-01_21-36-41](https://cloud.githubusercontent.com/assets/12874678/22525211/9fcff99a-e8c6-11e6-8647-49e1f59b79ea.jpg)
[WPN_BLSb_Norm_0xB9AB2301_ps.zip](https://github.com/KFreon/CSharpImageLibrary/files/745966/WPN_BLSb_Norm_0xB9AB2301_ps.zip)

**Comment by KFreon** [comment]
I'd say it's an artifact of the ATI2 compression scheme.  
Especially if all the other tools have the same "issue". Maybe to do with the optimisation part of it, it might be unable to match the colour exactly so it alters it a little to keep the general idea.
I dunno, but it probably won't be able to be fixed.

**Comment by starkgate** [comment]
I think you're right. Doing some more conversions, I noticed it didn't happen all the time. Which reassures me, because I thought that 1. I was blind for not seeing it before and 2. I'd have to redo all the norms.

Still, would be interesting to know why this happens...

**Comment by KFreon** [comment]
Indeed. These algorithms are a mystery to me despite using them all this time...
Anyway, I think this one is closed.
