### ISSUE TITLE
BMP to DXT1

### ISSUE THREAD

**Issue by starkgate** [KFreon/CSharpImageLibrary#18]
Same original texture as #17. I converted it from BMP to DXT1, successfully. The problem is that the output file can't be opened by either IE, PS, or anything. File is below.
[WPN_BLSb_Norm_0xB9AB2301_ps.zip](https://github.com/KFreon/CSharpImageLibrary/files/746016/WPN_BLSb_Norm_0xB9AB2301_ps.zip)

**Comment by KFreon** [comment]
Interesting...I can open it in ImageEngine, Paint.NET and ATI Compressonator, but not PS, DirectXTex, or GIMP.
I'll see what I can find.

**Comment by starkgate** [comment]
Really ? IE won't open it, for me. Interesting indeed... Reminds you of the good old times of testing for autofix ? :D

**Comment by KFreon** [comment]
What does ImageEngine say when trying to open it?

**Comment by starkgate** [comment]
It just displays a big red box with "LOAD FAILED" inside^^.

**Comment by KFreon** [comment]
My error messages need work...

**Comment by KFreon** [comment]
Fixed.
