### ISSUE TITLE
DXT A8R8B8G8 Files are broken

### ISSUE THREAD

**Issue by stricq** [KFreon/CSharpImageLibrary#2]
Image handling for A8R8B8G8 is broken.  files saved in this format are not viewable in other software.

**Comment by KFreon** [comment]
Can you give an example? 
I just tried opening one in dxtex and Photoshop. Worked fine.

**Comment by KFreon** [comment]
Closing for now due to lack of info.

**Comment by stricq** [comment]
Shoot!  I forgot about this.  Turns out it wasn't the A8R8G8B8 file format, it was the L8_G8 and your code is not broken, it's just a very uncommon format that most programs can't open.

**Comment by KFreon** [comment]
I was hoping it'd notify you :)
It is uncommon. As long as the toolset can open them, things that know about the format can open them too.
