### ISSUE TITLE
Crash when bulk converting BMP to DXT1

### ISSUE THREAD

**Issue by starkgate** [KFreon/CSharpImageLibrary#20]
May be related to #18 ?
![2017-02-06_16-13-44](https://cloud.githubusercontent.com/assets/12874678/22652628/755c262e-ec87-11e6-9ed6-1c10075e8509.png)

**Comment by KFreon** [comment]
I can't reproduce this either. More info?
Specifically, this crash is maybe from using the "Use source for destination" in Bulk Convert, so I need to know which setting you had.

**Comment by starkgate** [comment]
Ugh, I'm stupid. You're right, that was the cause. I accidentally unchecked the "Same as original" box in bulk convert, and left the text box empty. Hence the null exception.

Error message could be improved though :).

**Comment by KFreon** [comment]
Yes...The button should be grayed out if the box is empty. Will fix.

**Comment by starkgate** [comment]
I'm getting the same crash when using "Source format for saving". No matter whether "Same as original" is checked or not (with a new path).
