### ISSUE TITLE
Cannot open a DDS_ATI2 texture

### ISSUE THREAD

**Issue by starkgate** [KFreon/CSharpImageLibrary#21]
This is the debug log that the bulk converter outputs :
![2017-02-07_17-48-52](https://cloud.githubusercontent.com/assets/12874678/22701418/e3a27800-ed5d-11e6-88ec-ccf355e85583.png)

Loading the faulty texture alone results in a LOAD FAILED. The offending texture :
[0xD38F9A7B.zip](https://github.com/KFreon/CSharpImageLibrary/files/758501/0xD38F9A7B.zip)

Interestingly, old IE from ME3Explorer does open it. It's a 4x1 ratio texture, which may be the cause of the issue ?

**Comment by KFreon** [comment]
Yeah almost certainly a sizing issue.

**Comment by KFreon** [comment]
Hrm, that said, it works for me. Loaded first go.

You mention Bulk Converter, does it load properly just in the main window?

**Comment by starkgate** [comment]
No, I get a loud "one or more errors have occured" on 4.1.2. Better than load failed, although not hugely helpful :P.

**Comment by KFreon** [comment]
Hrm, I must have changed something. Can you give this one a quick go? It's just the latest stuff.
[TEST.zip](https://github.com/KFreon/CSharpImageLibrary/files/765409/TEST.zip)

**Comment by starkgate** [comment]
It loads perfectly. Well, nice work ! :)
