### ISSUE TITLE
Does not open textures from Mass Effect: Andromeda

### ISSUE THREAD

**Issue by munchyfly** [KFreon/CSharpImageLibrary#26]
The tool does not crash. It simply does not load the texture and throws the following error:

![screenshot_1](https://cloud.githubusercontent.com/assets/28280399/25969625/f7147c6a-366b-11e7-9fd5-00ccfe95c7be.png)

[HMF_HEAD_Jayde_Diff.zip](https://github.com/KFreon/CSharpImageLibrary/files/994271/HMF_HEAD_Jayde_Diff.zip)

**Comment by KFreon** [comment]
What an informative message I had it spit out. Really clears up the issue :P 
I'll see what I can find.
EDIT: Oohhhhh this is a DX10 thing. Hrm, I guess I'll have to figure those things out now then. Gonna be quite a while before that happens.

**Comment by munchyfly** [comment]
No problem. Take your time ^__^

**Comment by KFreon** [comment]
This will tie into #4. 
I'm working on it, but it's pretty damn complicated. In the meantime, try [DirectXTex.](https://github.com/Microsoft/DirectXTex)
Ideally I'd somehow use that in C#, but that's messy and didn't work well last time I tried.

I wouldn't expect anything from this for months yet :(

**Comment by KFreon** [comment]
Ok well [loading works](https://github.com/KFreon/CSharpImageLibrary/releases/tag/TEST), saving doesn't though.

**Comment by munchyfly** [comment]
Sorry for the late reply. Well, it's progress, isn't it? \o/

**Comment by KFreon** [comment]
Fixed in the newest version.
