### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nickbabcock** [KFreon/CSharpImageLibrary#30]
Hey! @Krakean alerted me to this wonderful repo. In it, it looks like you have a pure C# implementation of BC6 / BC7 decoding. I'm interested as I'm (very slowly) writing a pure C# dds decoding library (called [Pfim](https://github.com/nickbabcock/Pfim)), but I don't want to look too closely because I'm unsure of the license of this repo. If it happens to be liberally licensed, I'll incorporate the ideas according to the license .

**Comment by KFreon** [comment]
Hello!
That area of the code is mostly translated from the Microsoft [DirectXTex](https://github.com/Microsoft/DirectXTex), which is under MIT, so I suppose that's the licence for this as well.
Go for it :D

**Comment by nickbabcock** [comment]
Thank you 👏
