### ISSUE TITLE
No difference between ARGB and ABGR in preview image

### ISSUE THREAD

**Issue by Ryder25** [KFreon/CSharpImageLibrary#5]
I noticed that when previewing a dds file with ARGB, and ABGR, the file does not seem to change. The mask must not be getting applied correctly.

For example, a dds file with the same pixel data, and either of the following settings looks the same in a WPF image preview.

```
// ABGR
ddspf.rGBBitCount = 32;
ddspf.rBitMask = 0xFF;
ddspf.gBitMask = 0xFF00;
ddspf.bBitMask = 0xFF0000;
ddspf.aBitMask = 0xFF000000;
```

```
// ARGB
ddspf.rGBBitCount = 32;
ddspf.rBitMask = 0xFF0000;
ddspf.gBitMask = 0xFF00;
ddspf.bBitMask = 0xFF;
ddspf.aBitMask = 0xFF000000;
```

This image should have an orange border rather than a blue border in ABGR format.
[hard_icon.tga.zip](https://github.com/KFreon/CSharpImageLibrary/files/507493/hard_icon.tga.zip)

**Comment by KFreon** [comment]
Likely because I haven't thought about ABGR. 
At this stage, I don't really use the header. I'll have to fix that eventually.

**Comment by KFreon** [comment]
[This should be fixed now.](https://github.com/KFreon/CSharpImageLibrary/releases/tag/4.0)

**Comment by Ryder25** [comment]
Just did a quick test and seems to be working as advertised!

**Comment by KFreon** [comment]
Glad to hear :D
