### ISSUE TITLE
Quality Loss when converting normal maps to ATI2_3Dc format

### ISSUE THREAD

**Issue by forgetti** [KFreon/CSharpImageLibrary#6]
so this issue is prevalent when modding mass effect 2. essentially when converting a normal map from a format like DXT5 to ATI2_3Dc there is an dip in quality of the end result. 

for example when converting high res normal maps for tali this is the unconverted look: http://i.imgur.com/64HRn9u.png keep you eyes on the bottom of the texture

now this: http://i.imgur.com/Q33xRux.png is post autofix the normal map has lost most of it's depth and ingame the normal map has a few points where it's been inverted and on the neck plating there is a very visible shadow seam (can't provide screenshots at the moment. no saves.)

since initially bringing this problem up on the forums I tested a handful of other normal maps to find that similar errors occurred for instance an unusual shininess on the M92 Mantis in me2 although in it's raw form there is literally no visual difference on the normal map

this issue only occurs when converting to ATI2_3Dc, all other image formats work fine including converting to the V8U8 format that me3 uses

also here is the texture itself for testing: https://mega.nz/#!6F8lUSBR!6lhYd-jy5lPKq-6TPO4FUCCKwfVTzy09oHxEnxZX7Jo

I've tested this on both the 2.0 stable release through image engine and TPF/DDS tools and on the 3.0 stable release through TPF/DDS tools; both releases have the same problem.

(sorry if information is repeated. I've added as much new info as I can but I still don't have any me2 saves. I'll get 'em up when I can to provide screenshots of the problem)

edit 1: after further testing I've found something mind boggling. there is no quality loss when converting from ATI2_3Dc to V8U8

**Comment by KFreon** [comment]
[This should be fixed now.](https://github.com/KFreon/CSharpImageLibrary/releases/tag/4.0)
