### ISSUE TITLE
Image Engine: 3Dc textures mips

### ISSUE THREAD

**Issue by alvarome** [KFreon/CSharpImageLibrary#7]
Hi:

Once more, I´m not sure where to post this because I have no idea if I am working with faulty textures (most probably) or this is a toolset bug (I hope is not). 

I have a few ME2 upscaled 3Dc normals that all have one MIP less than expected. And that missing MIP is the 1x1 smaller one. That may explain why I have not noticed any vissual glitch ingame.

I loaded them in Stable 3.0 TPF Tools and after analysis those are not flagged. I´m unable to recall if this is correct -because these have equal or more mips than vanilla- or if should have been flagged because the mip count is not that expected for their size.

https://c2.staticflickr.com/6/5835/30578200632_9f6f429f2d_o.png

Those are installed anyway.

https://c2.staticflickr.com/6/5586/30063253614_90a0a69efa_o.png

I loaded one of those 3Dc normals in Image Engine:

https://c2.staticflickr.com/6/5833/30063253494_07d850a4a3_o.png

And, FWIW, this is the DDS header.

https://c2.staticflickr.com/6/5551/30395178150_b50d73bf2c_o.png

I tried to fix the mips using IE:

https://c2.staticflickr.com/6/5662/30606994491_18279cfa8f_o.png

But the resulting image has a wrong number of mips too:

https://c2.staticflickr.com/6/5802/30606994421_5f5f13a918_o.png

And this is the DDS header:

https://c2.staticflickr.com/6/5443/30695082335_a01938860b_o.png

But a workaround that fixed it was to remove all mips using IE:

https://c2.staticflickr.com/6/5550/30606994311_0da8f9fcdf_o.png

And, then, fixing that "no mips" texture with IE again:

https://c2.staticflickr.com/6/5449/30063252644_265e8e8c8e_o.png

So the new texture has the correct mips count.

https://c2.staticflickr.com/6/5734/30658181276_0b4d4ec9d3_o.png

I´m sorry to say I do not have knowlegde enough to determine what´s wrong in those textures but if anyone out there wanted to take a look, here you got:

https://mega.nz/#!cRJTxJyZ!mRN9sOUPRyfmSdmbmQ_0nF_qCtElQp0lHckbcZ6GX2w

I was aware of Mips issues in the past for V8U8 textures but these are 3Dc. I cannot tell for sure about it´s source but perhaps these came from faulty V8U8 ones. -?- No idea. 

Any input will be highly welcomed!

Regards!
Alvaro

**Comment by KFreon** [comment]
[Think this is fixed now.](https://github.com/KFreon/CSharpImageLibrary/releases/tag/4.0)
