### ISSUE TITLE
Setting maxDimension on non-square image causes incorrect DDS file read

### ISSUE THREAD

**Issue by Ryder25** [KFreon/CSharpImageLibrary#9]
I loaded a DXT5 512x256 1 mipmap image using this line:

```csharp
image = new CSharpImageLibrary.ImageEngineImage("filepath\temp.dds", 512);
```

When looking at var image in the debugger after this line, the Width/Height shows as 0.  I'm not sure if this is a problem with the image being non-square, or if there's a problem with the maxDimension setting. 
Default maxDimension setting of 0 seems to work just fine.

I don't get any exception with that line despite the problem. I did get an error when I tried to preview it in WPF from this method:

```csharp 
image.GetWPFBitmap(512, true);
```

Btw, considering the Debugger.Break() bug still seems to exist in .net framework, you may want to replace those with exceptions or something just in case.

**Comment by KFreon** [comment]
I thought I got rid of those Debugger things. I'll fix that.
And I'll check this out too.

Thanks for the detail in the report too :D

**Comment by KFreon** [comment]
Will upload a new version soonish.

**Comment by Ryder25** [comment]
Great work, thanks!
